### ISSUE TITLE
💭 진행 사항

### ISSUE THREAD

**Issue by seasameoil** [seasameoil/just-for-architecture#1]
## Description

구조 설계 내역 정리

## To-Do

- [ ] generic type 사용
- [ ] service, controller, entity 구조화
- [ ] 암호화, 복호화
- [ ] querydsl, jpa 사용

## ETC

기초적인 구조 정리 : ~7/5(수)
